base_symbol: "BTC"
quote_symbol: "USDT"
timeframe: "1m"
loop_seconds: 60
risk:
  max_position_usdt: 25
  max_open_trades: 3
  min_usdt_order: 5
strategy:
  use_trend: true
  use_dca: true
  use_martingale: true
  ema_fast: 9
  ema_slow: 21
  rsi_period: 14
  atr_period: 14
  dca_drop_pct: 1.0
  martingale_factor: 1.2
